
interfaces:
    - name: xe-0/0/0
      description: "connect srv1"
      vlan_id: 1
    - name: xe-0/0/1
      description: "connect srv2"
      vlan_id: 1
    - name: xe-0/0/2
      description: "connect srv3"
       vlan_id: 1
    - name: xe-0/0/3
      description: "connect srv4"
      vlan_id: 1
    - name: xe-0/0/4
      description: "connect bms"
      vlan_id: 1

irb_interfaces:
    - name: irb
      description: "vRouter Gateway for all srvs"
      ip: 172.16.1.254
      